# 1. Vectores, Matrices y Arreglos

## Librerias

In [1]:
import numpy as np

In [2]:
from scipy import sparse

## 1.1 Vectores

Crear vectores tipo fila

In [3]:
vector_fila = np.array([1,2,3])
vector_fila

array([1, 2, 3])

Crear vectores tipo columna

In [4]:
vector_columnas = np.array([[4],[5],[6]])
vector_columnas

array([[4],
       [5],
       [6]])

## 1.2 Matrices

Crear una matriz a traves de un array

In [5]:
matriz = np.array([
    [1,2],
    [3,4],
    [5,6]])

matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
matriz = np.mat([
    [1,2],
    [3,4],
    [5,6]
])

matriz

matrix([[1, 2],
        [3, 4],
        [5, 6]])

## 1.3 Matriz Dispersa

In [7]:
matriz = np.array([
    [0,0],
    [0,1],
    [3,0]
])

matriz

array([[0, 0],
       [0, 1],
       [3, 0]])

Cuando la mayoria de los elementos de una matriz tienen un valor igual a cero, esta se considere una **matriz dispersa**.

Una manera para evitar sesgos por la composición de esta matriz es utilizando CSR, que comprime los valores de la matriz y solo toma los valores de los elementos que son diferentes de cero.

Trabajando con una matriz dispersa.

In [8]:
matriz_dispersa = sparse.csr_matrix(matriz)
print(matriz_dispersa)

  (1, 1)	1
  (2, 0)	3


## 1.4 Seleccionando elementos

Seleccionando elementos de vectores y matrices

### Vectores

In [9]:
vector = np.array([1,2,3,4,5,6])

vector

array([1, 2, 3, 4, 5, 6])

In [10]:
# Seleccionar todos los elementos
vector[:]

array([1, 2, 3, 4, 5, 6])

In [11]:
# Seleccionar todo antes del tercer elemento
vector[:3]

array([1, 2, 3])

In [12]:
# Selecctionar el último elemento
vector[-1]

6

### Matrices

In [13]:
matriz = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Seleccionar las primeras dos filas y todas las columnas
matriz[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# Seleccionar todas las filas de la segunda columna
matriz[:,1:2]

array([[2],
       [5],
       [8]])

## 1.5 Describiendo una matriz

In [16]:
# Conocer las dimensiones de la matriz
matriz.shape

(3, 3)

In [17]:
# Ver el número de elementos
matriz.size

9

In [18]:
# Ver el número de dimensiones
matriz.ndim

2

## 1.6 Aplicando operaciones a los elementos

In [19]:
# Creamos una función que sume 100 
suma_100 = lambda x: x + 100

In [20]:
# Creamos una función vectorizada
suma_100_vec = np.vectorize(suma_100)

In [21]:
# Aplicamos la función vectorizada a nuestro vector
suma_100_vec(matriz)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [22]:
# Tambien podemos hacerlo de manera directa
matriz + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.7 Encontrando valores máximos y mínimos

In [23]:
# Encontrar el valor máximo
np.max(matriz)

9

In [24]:
# Encontrar el valor mínimo
np.min(matriz)

1

In [25]:
# Podemos encontrar los valores máximos para las filas o columnas
np.max(matriz, axis=0), np.max(matriz, axis=1)

(array([7, 8, 9]), array([3, 6, 9]))

In [26]:
# Podemos encontrar los valores mínimos para las filas o columnas
np.min(matriz, axis=0), np.min(matriz, axis=1)

(array([1, 2, 3]), array([1, 4, 7]))

## 1.8 Calculando promedio, varianza y desviación estándar

In [27]:
# Promedio
np.mean(matriz)

5.0

In [28]:
# Varianza
np.var(matriz)

6.666666666666667

In [29]:
# Desviación estándar
np.std(matriz)

2.581988897471611

## 1.9 Reorganizando arrays

In [30]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matriz.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## 1.10 Trasponiendo vectores o matrices

In [32]:
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 1.11 Aplastar una matriz

In [33]:
matriz.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.12 Encontrar el rango de una matriz

In [34]:
np.linalg.matrix_rank(matriz)

2

## 1.13 Calcular el determinante

In [35]:
np.linalg.det(matriz)

-9.51619735392994e-16

## 1.14 Llamar la diagonal de una matriz

In [36]:
# Llamando a la diagonal principal
matriz.diagonal()

array([1, 5, 9])

In [38]:
# Llamando a las diagonales secundarias
matriz.diagonal(offset=1), matriz.diagonal(offset=-1)

(array([2, 6]), array([4, 8]))

## 1.15 Calculando el trazo de una matriz

In [39]:
matriz.trace()

15

## 1.16 Encontrar Eigenvalores y Eigenvectores

In [40]:
eigenvalores, eigenvectores = np.linalg.eig(matriz)

In [41]:
eigenvalores

array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16])

In [42]:
eigenvectores

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

## 1.17 Calculando el producto punto

In [43]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [44]:
np.dot(vector_a, vector_b)

32

## 1.18 Sumar y restar matrices

In [45]:
matriz_a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matriz_b = np.array([
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [46]:
np.add(matriz_a, matriz_b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [47]:
np.subtract(matriz_b, matriz_a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

## 1.19 Multiplicando matrices

In [48]:
np.dot(matriz_a, matriz_b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

In [50]:
matriz_a @ matriz_b

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

## 1.20 Invertir una matriz

np.linalg.inv(matriz)

In [57]:
matriz @ np.linalg.inv(matriz)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

## 1.21 Gererando valores aleatorios

In [68]:
# Establecer la semilla
np.random.seed(0)

In [62]:
# Generar un array con valores aleatorios entre 0 y 1
np.random.random(3)

array([0.0514672 , 0.44080984, 0.02987621])

In [64]:
# Generar valores aleatorios entre un rango
np.random.randint(1,100,3)

array([91, 23, 67])

In [65]:
# Generar valores aleatorios de una distribución normal con media cero y desviación estandar 1
np.random.normal(0, 1, 3)

array([-0.34733018,  0.06629873, -1.62758528])

In [66]:
# Generar valores aleatorios de una distribución logistica con media cero y desviación estandar 1
np.random.logistic(0, 1, 3)

array([-0.34291651, -0.92704265,  0.81483059])

In [67]:
# Generar valores aleatorios entre un rando
np.random.uniform(1, 2, 3)

array([1.44045372, 1.15686774, 1.54464902])