# 1. Vectores, Matrices y Arreglos

## Librerias

In [1]:
import numpy as np

In [2]:
from scipy import sparse

## 1.1 Vectores

Crear vectores tipo fila

In [3]:
vector_fila = np.array([1,2,3])
vector_fila

array([1, 2, 3])

Crear vectores tipo columna

In [4]:
vector_columnas = np.array([[4],[5],[6]])
vector_columnas

array([[4],
       [5],
       [6]])

## 1.2 Matrices

Crear una matriz a traves de un array

In [5]:
matriz = np.array([
    [1,2],
    [3,4],
    [5,6]])

matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
matriz = np.mat([
    [1,2],
    [3,4],
    [5,6]
])

matriz

matrix([[1, 2],
        [3, 4],
        [5, 6]])

## 1.3 Matriz Dispersa

In [7]:
matriz = np.array([
    [0,0],
    [0,1],
    [3,0]
])

matriz

array([[0, 0],
       [0, 1],
       [3, 0]])

Cuando la mayoria de los elementos de una matriz tienen un valor igual a cero, esta se considere una **matriz dispersa**.

Una manera para evitar sesgos por la composición de esta matriz es utilizando CSR, que comprime los valores de la matriz y solo toma los valores de los elementos que son diferentes de cero.

Trabajando con una matriz dispersa.

In [8]:
matriz_dispersa = sparse.csr_matrix(matriz)
print(matriz_dispersa)

  (1, 1)	1
  (2, 0)	3


## 1.4 Seleccionando elementos

Seleccionando elementos de vectores y matrices

### Vectores

In [94]:
vector = np.array([1,2,3,4,5,6])

vector

array([1, 2, 3, 4, 5, 6])

In [101]:
# Seleccionar todos los elementos
vector[:]

array([1, 2, 3, 4, 5, 6])

In [104]:
# Seleccionar todo antes del tercer elemento
vector[:3]

array([1, 2, 3])

In [103]:
# Selecctionar el último elemento
vector[-1]

6

### Matrices

In [96]:
matriz = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
# Seleccionar las primeras dos filas y todas las columnas
matriz[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
# Seleccionar todas las filas de la segunda columna
matriz[:,1:2]

array([[2],
       [5],
       [8]])

## 1.5 Describiendo una matriz

In [111]:
matriz = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
# Conocer las dimensiones de la matriz
matriz.shape

(3, 4)

In [114]:
# Ver el número de elementos
matriz.size

12

In [116]:
# Ver el número de dimensiones
matriz.ndim

2