## Librerias

In [1]:
import numpy as np

In [14]:
from scipy import sparse

## 1. Vectores

Crear vectores tipo fila

In [4]:
vector_fila = np.array([1,2,3])
vector_fila

array([1, 2, 3])

Crear vectores tipo columna

In [6]:
vector_columnas = np.array([[4],[5],[6]])
vector_columnas

array([[4],
       [5],
       [6]])

## 2. Matrices

Crear una matriz a traves de un array

In [11]:
matriz = np.array([
    [1,2],
    [3,4],
    [5,6]])

matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
matriz = np.mat([
    [1,2],
    [3,4],
    [5,6]
])

matriz

matrix([[1, 2],
        [3, 4],
        [5, 6]])

Una **matriz dispersa** es aquella que contiene varios elementos con valor igual a cero

Trabajando con una matriz dispersa

In [17]:
matriz = np.array([
    [0,0],
    [0,1],
    [3,0]
])

matriz

array([[0, 0],
       [0, 1],
       [3, 0]])

In [19]:
matriz_dispersa = sparse.csr_matrix(matriz)
print(matriz_dispersa)

  (1, 1)	1
  (2, 0)	3
