## 2. Cargando datos

## Librerias

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_columns = False

In [3]:
from sklearn import datasets

## 2.1 Cargando un dataset de muestra

In [4]:
digitos = datasets.load_digits()

In [6]:
features = digitos.data

In [7]:
features

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [18]:
features[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [10]:
target = digitos.target

In [11]:
target

array([0, 1, 2, ..., 8, 9, 8])

## 2.2 Crear una simulación

In [19]:
from sklearn.datasets import make_regression

**Dataset para Regresión Lineal**

In [20]:
# Generamos una matriz de features, un vector objetivo y los coeficientes
features, target, coeficientes = make_regression(
    n_samples=100, 
    n_features=3, 
    n_informative=3, 
    n_targets=1,
    noise=0.0, 
    coef=True,
    random_state=1
)

In [30]:
print('Matriz de features')
print(' ')
print(features[:3])
print('')
print('Vector Objetivo')
print('')
print(target[:3])

Matriz de features
 
[[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]

Vector Objetivo

[-10.37865986  25.5124503   19.67705609]


**Dataset para Regresión Logistica**

In [24]:
from sklearn.datasets import make_classification

In [ ]:
features, target, coeficientes = make_classification()